"""
topic_categorizer.py
--------------------
Categorize each meeting into a small set of stakeholder-relevant themes.

APPROACH (hybrid):

  Step 1 — Use the rich `topics` field already present in summary.json (these
           were generated by an upstream LLM and are high-quality signal).
           We canonicalize them into a fixed taxonomy of 8 themes.

  Step 2 — Independently CLUSTER the transcripts via TF-IDF + KMeans to
           sanity-check the taxonomy. If the clusters align with our taxonomy,
           that is supporting evidence the taxonomy is real, not arbitrary.

WHY HYBRID, NOT PURE LLM-TOPIC-CALL?
  * The upstream pipeline already paid for the LLM call once. Re-running an
    LLM categorization on every transcript is wasteful and non-deterministic.
  * A fixed taxonomy with a transparent keyword map is auditable — a Product
    Manager can read it, push back, and propose changes.
  * Clustering on TF-IDF gives us a second, independent view that catches
    blind spots in the keyword map.
  * For genuinely ambiguous meetings we could LLM-classify, but for this
    dataset the taxonomy hits everything cleanly.

THE 8 THEMES (chosen to map to who-cares-about-what):
  1. Reliability & Incidents      → eng leadership, SRE
  2. Renewal & Churn Risk         → CS, sales leadership
  3. Compliance & Audit           → product, security
  4. Product Launch & Adoption    → PM, growth
  5. Roadmap & Planning           → eng leadership, PM
  6. Support & Bug Resolution     → support leadership
  7. Pricing & Commercial         → sales, finance
  8. Competitive Intelligence     → PM, marketing

A meeting can belong to MULTIPLE themes (real life is messy). We surface
both the primary theme and any secondary ones above a threshold.
"""

from __future__ import annotations

import numpy as np
import pandas as pd

# ----- The taxonomy: theme -> set of topic-keywords / fragments -----
# Match is case-insensitive substring on the meeting's `topics` list AND
# on the meeting title (title carries strong signal too).
THEMES: dict[str, list[str]] = {
    "Reliability & Incidents": [
        "outage", "incident", "postmortem", "post-mortem", "post-incident",
        "infrastructure reliability", "rca", "root cause", "war room",
        "service outage", "platform outage", "remediation", "downtime",
        "sla breach", "reliability", "performance", "scalability",
    ],
    "Renewal & Churn Risk": [
        "renewal", "churn risk", "churn", "retention", "expansion",
        "contract", "win/loss",
    ],
    "Compliance & Audit": [
        "compliance", "audit", "soc 2", "soc2", "iso 27001", "hipaa",
        "pci dss", "pci", "framework", "evidence", "control",
        "compliance reporting", "multi-framework",
    ],
    "Product Launch & Adoption": [
        "product launch", "launch readiness", "ga deployment", "rollout",
        "onboarding", "adoption metrics", "feature adoption", "design review",
        "go-to-market", "comply v2 launch", "launch day",
    ],
    "Roadmap & Planning": [
        "roadmap", "sprint planning", "sprint retro", "quarterly planning",
        "q2 planning", "q1 planning", "all hands", "product sync",
        "planning",
    ],
    "Support & Bug Resolution": [
        "support case", "support ticket", "support response time",
        "technical issue", "product bug", "workaround", "billing dispute",
        "troubleshooting", "feature request",
    ],
    "Pricing & Commercial": [
        "pricing", "price", "discount", "billing", "contract discussion",
        "sla credit",
    ],
    "Competitive Intelligence": [
        "competitive", "competitor", "competitive evaluation", "win/loss",
        "sentinelshield",
    ],
}


def _theme_score(topics: list[str], title: str) -> dict[str, float]:
    """Score each theme by counting keyword hits in the topic list + title."""
    text = " || ".join(topics + [title]).lower()
    scores: dict[str, float] = {}
    for theme, kws in THEMES.items():
        # weight: each keyword hit = 1; title hit weighted slightly higher
        hits = sum(1 for kw in kws if kw in text)
        # title-only hits get a small bonus to disambiguate
        title_hits = sum(1 for kw in kws if kw in title.lower())
        scores[theme] = hits + 0.5 * title_hits
    return scores


def categorize_one(topics: list[str], title: str,
                   secondary_threshold: float = 0.5) -> dict:
    """Return primary theme + list of secondaries."""
    scores = _theme_score(topics, title)
    if max(scores.values()) == 0:
        return {"primary": "Other", "primary_score": 0.0, "secondary": [], "scores": scores}
    # Primary = top-scoring theme
    primary = max(scores, key=scores.get)
    primary_score = scores[primary]
    # Secondaries: anything else with score >= threshold * primary_score
    cutoff = max(secondary_threshold * primary_score, 1.0)
    secondaries = sorted(
        [t for t, s in scores.items() if t != primary and s >= cutoff],
        key=lambda t: -scores[t],
    )
    return {
        "primary": primary,
        "primary_score": primary_score,
        "secondary": secondaries,
        "scores": scores,
    }


def categorize_all(meetings_frame: pd.DataFrame) -> pd.DataFrame:
    """Add primary_theme, secondary_themes columns."""
    out = meetings_frame.copy()
    enriched = out.apply(
        lambda r: categorize_one(r["topics"], r["title"]), axis=1
    )
    out["primary_theme"] = enriched.apply(lambda d: d["primary"])
    out["secondary_themes"] = enriched.apply(lambda d: d["secondary"])
    out["theme_scores"] = enriched.apply(lambda d: d["scores"])
    return out


# ----- Independent sanity check: TF-IDF + KMeans clustering -----

def cluster_sanity_check(meetings, k: int = 8) -> pd.DataFrame:
    """
    Independent clustering of transcripts to validate taxonomy.

    Returns a DataFrame with cluster_id and the top distinctive terms per
    cluster — we then eyeball whether the clusters look like our themes.
    """
    from sklearn.cluster import KMeans
    from sklearn.feature_extraction.text import TfidfVectorizer

    docs = [m.full_text for m in meetings]
    vec = TfidfVectorizer(
        max_features=2000,
        stop_words="english",
        ngram_range=(1, 2),
        min_df=2,
        max_df=0.6,
    )
    X = vec.fit_transform(docs)
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = km.fit_predict(X)

    terms = np.array(vec.get_feature_names_out())
    rows = []
    for c in range(k):
        # Top terms by cluster centroid
        centroid = km.cluster_centers_[c]
        top_idx = centroid.argsort()[::-1][:10]
        rows.append({
            "cluster_id": c,
            "n_meetings": int((labels == c).sum()),
            "top_terms": ", ".join(terms[top_idx]),
        })
    return pd.DataFrame(rows), labels
